version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vehicle
    container_name: vehicle-app
    restart: unless-stopped
    ports:
      - 5000:5000
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    tty: true
    networks:
      - vehicle-net

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: vehicle-db
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - vehicle-net

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - vehicle-net

  nginx:
    image: nginx:alpine
    container_name: vehicle-nginx
    restart: unless-stopped
    ports:
      - 7000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - vehicle-net

networks:
  vehicle-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
